#!/bin/sh

e=0

set -x
export CGO_ENABLED=1
go test -race                 ./... || e=1
go test -race -tags=testpq    ./... || e=1
go test -race -tags=testpgx   ./... || e=1
go test -race -tags=testmaria ./... || e=1
exit $e
