#!/bin/sh

e=0

set -x
export CGO_ENABLED=1
go test ./... || e=1

export CGO_ENABLED=0
go test -tags=testpq  ./... || e=1
go test -tags=testpgx ./... || e=1
# go test -race -tags=testmaria ./... || e=1

exit $e
